# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd5f3152af296192ec9c876aaa08409930595dc6688e23b293765708acd6fcb9cb23753ec23278e72e3efca4866ca6ed34b6abd2fe8336447e5ba63a2fa20b4c

test:
  secret_key_base: 0594b716e891a0ff129c09f3eacfa76a5c00ceb4d35d007faaf5dd6054033a903b30904abe252acfa612debec1a7a30ab5efa86dc76a2a5a82bc7189d352eb4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
