# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66d60a18c17693253a9be26be35f105b637ad7b5b140351ec022736a2fe161901f6c912fd9fdb1c711d6a13a14e57e5ae6349d356fb87133f8c43091715df520

test:
  secret_key_base: 9d4b7d84bbe59b668ffc3b488556f216ac5b57114450f49dce7da1cc970fb364219e41ccdcbfcb6fadb283543e61f43eecd90dcdec06ed9561b2e0e14d3fc9d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
